name: Python Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the application
      run: |
        export DATABASE_URL="sqlite:///$(pwd)/materials.db"
        export JWT_SECRET_KEY="your_secret_key"
        export PORT="5000"
        python app.py
